### ISSUE TITLE
How can we use caching to reduce overhead?

### ISSUE THREAD

**Issue by dreamingmind** [OrigamiStructures/Cake3xMarkdown#2]

**Comment by dreamingmind** [comment]
We could have a place to store a supplied cache key. Then if a key exists we read the cache and return the result. If the read gets nothing then parse and cache the results. And if no cache key exists, just parse and return.

``` php
// pseudo code
$out = null;
if ( $this->cacheKey ) {
    $out = Cache::read( $this->cacheKey );
}
if ( is_null($out) {
    // transform the text
    if ( $this->cacheKey ) {
        Cache::write( $this->cacheKey);
    }
}
return $out;
```

This means we'd have to integrate cache management into the model to insure the cache got cleared properly.

Accepting any cacheKey from code external to the Helper (rather that programatically creating it, eg: `$modified . $id` ) is a trade off. It means that the implementation code must always provide this value to properly use caching. But it also means the developer can use any cache key construction they want. They could have multiple cached versions of the same record data (like a full and a summary cache)

**Comment by dreamingmind** [comment]
What if we made 'automatic' internal caching that was carried out by a callable property that the user could configure?

Then we could accommodate any key generation scheme and also make the cache use more automated.

This means calls wouldn't be made with simple text blocks. Rather, an entity would be sent in and some mapping stored in the Helper so the code could find the markdown text and the values to use in cache key generation.

**Comment by curlyjason** [comment]
Your second thought seems more in line with what we program like. Do you think this would be difficult to implement? It seems like a trait would need to be written to manage this.

**Comment by dreamingmind** [comment]
I don't know how this would work actually. Maybe I'll poke around a little and see how a callable can be passed into a helper
